name: chomu
description: Meme Factory.

publish_to: 'none' 
version: 0.2.1+21


environment:        
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flex_color_scheme: ^5.0.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_storage: ^10.2.8
  firebase_messaging: ^12.0.1
  firebase_analytics: ^9.1.1
  firebase_crashlytics: ^2.6.3
  cloud_firestore: ^3.1.13  
  get_storage: ^2.0.3
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  visibility_detector: ^0.3.3
  dropdown_button2: ^1.4.0
  share_plus: ^4.0.4
  settings_ui: ^2.0.2  
  url_launcher: ^6.1.0
  awesome_notifications: ^0.6.21
  flutter_native_splash: ^2.1.6
  loading_animation_widget: ^1.1.0+3
  video_player: ^2.4.0
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  wakelock: ^0.6.1+2
  flutter_file_downloader: ^1.0.14
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  in_app_review: ^2.0.4
  google_mobile_ads: ^2.0.0
  rating_dialog: ^2.0.4
  font_awesome_flutter: ^10.1.0
  device_info_plus: ^4.0.0
  introduction_screen: ^3.0.2
  flutter_material_pickers: ^3.1.4+1
  file_picker: ^4.5.1
  webview_flutter: ^3.0.4
  import_sorter: ^4.6.0
  google_fonts: ^3.0.1
  json_to_model: ^3.1.8+beta
  quiver: ^3.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true

  assets:
     - assets/images/

flutter_native_splash:
  color: "#673AB7"
  image : assets/images/logo.png
  android_12:
    color: "#673AB7"
    icon_background_color: "#673AB7"